Update copy

diff --git a/proper b/proper
--- a/proper
+++ b/proper
@@ -4,7 +4,7 @@
 # ERROR: Let the user know if the script fails
 ###############################################################################
 
-trap 'ret=$?; test $ret -ne 0 && printf "\n\e[31m=====  The script has failed to run. Please try again.  =====\033[0m\n" >&2; exit $ret' EXIT
+trap 'ret=$?; test $ret -ne 0 && printf "\n\e[31m=====  Proper has failed to complete.  =====\033[0m\n" >&2; exit $ret' EXIT
 set -e
 
 ###############################################################################
@@ -146,7 +146,7 @@ fi
 ###############################################################################
 chapter "Custom Scripts"
 if [ -f "$HOME/.proper-custom" ]; then
-	if ask "Do you run custom scripts?" Y; then
+	if ask "Found custom scripts at "$HOME/.proper-custom". Would like you like run this file?" Y; then
 		. "$HOME/.proper-custom"
 		printf "\n  Custom scripts found. \n"
 	else
